include(../libraries/ArduinoMqtt/ArduinoMqtt.pri)
include(../libraries/FastLED/FastLED.pri)
include(../libraries/common/common.pri)
include(../libraries/Lights/lights.pri)
include(../libraries/ArduinoMqtt/ArduinoMqtt.pri)
include(../libraries/ArduinoJson/ArduinoJson.pri)
include(../libraries/NodeEngine/node-engine.pri)
include(../KitchenLight/kitchen-light.pri)
