HEADERS += \
    $$PWD/ArduinoJson.h \
    $$PWD/extras/tests/Helpers/Arduino.h \
    $$PWD/extras/tests/Helpers/CustomReader.hpp \
    $$PWD/extras/tests/Helpers/api/Print.h \
    $$PWD/extras/tests/Helpers/api/Stream.h \
    $$PWD/extras/tests/Helpers/api/String.h \
    $$PWD/extras/tests/Helpers/progmem_emulation.hpp \
    $$PWD/extras/tests/Misc/custom_string.hpp \
    $$PWD/extras/tests/Misc/weird_strcmp.hpp \
    $$PWD/extras/tests/catch/catch.hpp \
    $$PWD/src/ArduinoJson.h \
    $$PWD/src/ArduinoJson.hpp \
    $$PWD/src/ArduinoJson/Array/ArrayFunctions.hpp \
    $$PWD/src/ArduinoJson/Array/ArrayImpl.hpp \
    $$PWD/src/ArduinoJson/Array/ArrayIterator.hpp \
    $$PWD/src/ArduinoJson/Array/ArrayRef.hpp \
    $$PWD/src/ArduinoJson/Array/ArrayShortcuts.hpp \
    $$PWD/src/ArduinoJson/Array/ElementProxy.hpp \
    $$PWD/src/ArduinoJson/Array/Utilities.hpp \
    $$PWD/src/ArduinoJson/Collection/CollectionData.hpp \
    $$PWD/src/ArduinoJson/Collection/CollectionImpl.hpp \
    $$PWD/src/ArduinoJson/Configuration.hpp \
    $$PWD/src/ArduinoJson/Deserialization/DeserializationError.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Filter.hpp \
    $$PWD/src/ArduinoJson/Deserialization/NestingLimit.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Reader.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Readers/ArduinoStreamReader.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Readers/ArduinoStringReader.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Readers/FlashReader.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Readers/IteratorReader.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Readers/RamReader.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Readers/StdStreamReader.hpp \
    $$PWD/src/ArduinoJson/Deserialization/Readers/VariantReader.hpp \
    $$PWD/src/ArduinoJson/Deserialization/deserialize.hpp \
    $$PWD/src/ArduinoJson/Document/BasicJsonDocument.hpp \
    $$PWD/src/ArduinoJson/Document/DynamicJsonDocument.hpp \
    $$PWD/src/ArduinoJson/Document/JsonDocument.hpp \
    $$PWD/src/ArduinoJson/Document/StaticJsonDocument.hpp \
    $$PWD/src/ArduinoJson/Json/EscapeSequence.hpp \
    $$PWD/src/ArduinoJson/Json/JsonDeserializer.hpp \
    $$PWD/src/ArduinoJson/Json/JsonSerializer.hpp \
    $$PWD/src/ArduinoJson/Json/Latch.hpp \
    $$PWD/src/ArduinoJson/Json/PrettyJsonSerializer.hpp \
    $$PWD/src/ArduinoJson/Json/TextFormatter.hpp \
    $$PWD/src/ArduinoJson/Json/Utf16.hpp \
    $$PWD/src/ArduinoJson/Json/Utf8.hpp \
    $$PWD/src/ArduinoJson/Memory/Alignment.hpp \
    $$PWD/src/ArduinoJson/Memory/MemoryPool.hpp \
    $$PWD/src/ArduinoJson/Misc/SerializedValue.hpp \
    $$PWD/src/ArduinoJson/Misc/Visitable.hpp \
    $$PWD/src/ArduinoJson/MsgPack/MsgPackDeserializer.hpp \
    $$PWD/src/ArduinoJson/MsgPack/MsgPackSerializer.hpp \
    $$PWD/src/ArduinoJson/MsgPack/endianess.hpp \
    $$PWD/src/ArduinoJson/MsgPack/ieee754.hpp \
    $$PWD/src/ArduinoJson/Namespace.hpp \
    $$PWD/src/ArduinoJson/Numbers/Float.hpp \
    $$PWD/src/ArduinoJson/Numbers/FloatParts.hpp \
    $$PWD/src/ArduinoJson/Numbers/FloatTraits.hpp \
    $$PWD/src/ArduinoJson/Numbers/Integer.hpp \
    $$PWD/src/ArduinoJson/Numbers/arithmeticCompare.hpp \
    $$PWD/src/ArduinoJson/Numbers/convertNumber.hpp \
    $$PWD/src/ArduinoJson/Numbers/parseNumber.hpp \
    $$PWD/src/ArduinoJson/Object/MemberProxy.hpp \
    $$PWD/src/ArduinoJson/Object/ObjectFunctions.hpp \
    $$PWD/src/ArduinoJson/Object/ObjectImpl.hpp \
    $$PWD/src/ArduinoJson/Object/ObjectIterator.hpp \
    $$PWD/src/ArduinoJson/Object/ObjectRef.hpp \
    $$PWD/src/ArduinoJson/Object/ObjectShortcuts.hpp \
    $$PWD/src/ArduinoJson/Object/Pair.hpp \
    $$PWD/src/ArduinoJson/Polyfills/alias_cast.hpp \
    $$PWD/src/ArduinoJson/Polyfills/assert.hpp \
    $$PWD/src/ArduinoJson/Polyfills/attributes.hpp \
    $$PWD/src/ArduinoJson/Polyfills/ctype.hpp \
    $$PWD/src/ArduinoJson/Polyfills/integer.hpp \
    $$PWD/src/ArduinoJson/Polyfills/limits.hpp \
    $$PWD/src/ArduinoJson/Polyfills/math.hpp \
    $$PWD/src/ArduinoJson/Polyfills/mpl/max.hpp \
    $$PWD/src/ArduinoJson/Polyfills/pgmspace.hpp \
    $$PWD/src/ArduinoJson/Polyfills/pgmspace_generic.hpp \
    $$PWD/src/ArduinoJson/Polyfills/preprocessor.hpp \
    $$PWD/src/ArduinoJson/Polyfills/safe_strcmp.hpp \
    $$PWD/src/ArduinoJson/Polyfills/static_array.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/conditional.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/declval.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/enable_if.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/integral_constant.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_array.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_base_of.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_class.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_const.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_convertible.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_enum.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_floating_point.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_integral.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_pointer.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_same.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_signed.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/is_unsigned.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/make_unsigned.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/make_void.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/remove_const.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/remove_cv.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/remove_reference.hpp \
    $$PWD/src/ArduinoJson/Polyfills/type_traits/type_identity.hpp \
    $$PWD/src/ArduinoJson/Polyfills/utility.hpp \
    $$PWD/src/ArduinoJson/Serialization/CountingDecorator.hpp \
    $$PWD/src/ArduinoJson/Serialization/Writer.hpp \
    $$PWD/src/ArduinoJson/Serialization/Writers/ArduinoStringWriter.hpp \
    $$PWD/src/ArduinoJson/Serialization/Writers/DummyWriter.hpp \
    $$PWD/src/ArduinoJson/Serialization/Writers/PrintWriter.hpp \
    $$PWD/src/ArduinoJson/Serialization/Writers/StaticStringWriter.hpp \
    $$PWD/src/ArduinoJson/Serialization/Writers/StdStreamWriter.hpp \
    $$PWD/src/ArduinoJson/Serialization/Writers/StdStringWriter.hpp \
    $$PWD/src/ArduinoJson/Serialization/measure.hpp \
    $$PWD/src/ArduinoJson/Serialization/serialize.hpp \
    $$PWD/src/ArduinoJson/StringStorage/StringCopier.hpp \
    $$PWD/src/ArduinoJson/StringStorage/StringMover.hpp \
    $$PWD/src/ArduinoJson/StringStorage/StringStorage.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/ArduinoStringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/ConstRamStringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/FlashStringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/JsonStringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/RamStringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/SizedFlashStringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/SizedRamStringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/StdStringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/Adapters/StringViewAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/IsWriteableString.hpp \
    $$PWD/src/ArduinoJson/Strings/StoragePolicy.hpp \
    $$PWD/src/ArduinoJson/Strings/String.hpp \
    $$PWD/src/ArduinoJson/Strings/StringAdapter.hpp \
    $$PWD/src/ArduinoJson/Strings/StringAdapters.hpp \
    $$PWD/src/ArduinoJson/Variant/Converter.hpp \
    $$PWD/src/ArduinoJson/Variant/ConverterImpl.hpp \
    $$PWD/src/ArduinoJson/Variant/SlotFunctions.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantCompare.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantContent.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantData.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantFunctions.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantImpl.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantOperators.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantRef.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantShortcuts.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantSlot.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantTag.hpp \
    $$PWD/src/ArduinoJson/Variant/VariantTo.hpp \
    $$PWD/src/ArduinoJson/Variant/Visitor.hpp \
    $$PWD/src/ArduinoJson/compatibility.hpp \
    $$PWD/src/ArduinoJson/version.hpp

SOURCES += \
    $$PWD/extras/ci/espidf/main/main.cpp \
    $$PWD/extras/fuzzing/json_fuzzer.cpp \
    $$PWD/extras/fuzzing/msgpack_fuzzer.cpp \
    $$PWD/extras/fuzzing/reproducer.cpp \
    $$PWD/extras/scripts/wandbox/JsonGeneratorExample.cpp \
    $$PWD/extras/scripts/wandbox/JsonParserExample.cpp \
    $$PWD/extras/scripts/wandbox/MsgPackParserExample.cpp \
    $$PWD/extras/tests/Cpp11/issue1120.cpp \
    $$PWD/extras/tests/Cpp11/nullptr.cpp \
    $$PWD/extras/tests/Cpp11/use_long_long_0.cpp \
    $$PWD/extras/tests/Cpp11/use_long_long_1.cpp \
    $$PWD/extras/tests/Cpp17/string_view.cpp \
    $$PWD/extras/tests/Cpp20/smoke_test.cpp \
    $$PWD/extras/tests/FailingBuilds/Issue1189.cpp \
    $$PWD/extras/tests/FailingBuilds/Issue978.cpp \
    $$PWD/extras/tests/FailingBuilds/assign_char.cpp \
    $$PWD/extras/tests/FailingBuilds/delete_jsondocument.cpp \
    $$PWD/extras/tests/FailingBuilds/read_long_long.cpp \
    $$PWD/extras/tests/FailingBuilds/variant_as_char.cpp \
    $$PWD/extras/tests/FailingBuilds/write_long_long.cpp \
    $$PWD/extras/tests/IntegrationTests/gbathree.cpp \
    $$PWD/extras/tests/IntegrationTests/issue772.cpp \
    $$PWD/extras/tests/IntegrationTests/openweathermap.cpp \
    $$PWD/extras/tests/IntegrationTests/round_trip.cpp \
    $$PWD/extras/tests/JsonArray/add.cpp \
    $$PWD/extras/tests/JsonArray/clear.cpp \
    $$PWD/extras/tests/JsonArray/copyArray.cpp \
    $$PWD/extras/tests/JsonArray/createNested.cpp \
    $$PWD/extras/tests/JsonArray/equals.cpp \
    $$PWD/extras/tests/JsonArray/get.cpp \
    $$PWD/extras/tests/JsonArray/isNull.cpp \
    $$PWD/extras/tests/JsonArray/iterator.cpp \
    $$PWD/extras/tests/JsonArray/memoryUsage.cpp \
    $$PWD/extras/tests/JsonArray/nesting.cpp \
    $$PWD/extras/tests/JsonArray/remove.cpp \
    $$PWD/extras/tests/JsonArray/size.cpp \
    $$PWD/extras/tests/JsonArray/std_string.cpp \
    $$PWD/extras/tests/JsonArray/subscript.cpp \
    $$PWD/extras/tests/JsonArray/undefined.cpp \
    $$PWD/extras/tests/JsonDeserializer/DeserializationError.cpp \
    $$PWD/extras/tests/JsonDeserializer/array.cpp \
    $$PWD/extras/tests/JsonDeserializer/array_static.cpp \
    $$PWD/extras/tests/JsonDeserializer/filter.cpp \
    $$PWD/extras/tests/JsonDeserializer/incomplete_input.cpp \
    $$PWD/extras/tests/JsonDeserializer/input_types.cpp \
    $$PWD/extras/tests/JsonDeserializer/invalid_input.cpp \
    $$PWD/extras/tests/JsonDeserializer/misc.cpp \
    $$PWD/extras/tests/JsonDeserializer/nestingLimit.cpp \
    $$PWD/extras/tests/JsonDeserializer/number.cpp \
    $$PWD/extras/tests/JsonDeserializer/object.cpp \
    $$PWD/extras/tests/JsonDeserializer/object_static.cpp \
    $$PWD/extras/tests/JsonDeserializer/string.cpp \
    $$PWD/extras/tests/JsonDocument/BasicJsonDocument.cpp \
    $$PWD/extras/tests/JsonDocument/DynamicJsonDocument.cpp \
    $$PWD/extras/tests/JsonDocument/ElementProxy.cpp \
    $$PWD/extras/tests/JsonDocument/MemberProxy.cpp \
    $$PWD/extras/tests/JsonDocument/StaticJsonDocument.cpp \
    $$PWD/extras/tests/JsonDocument/add.cpp \
    $$PWD/extras/tests/JsonDocument/compare.cpp \
    $$PWD/extras/tests/JsonDocument/containsKey.cpp \
    $$PWD/extras/tests/JsonDocument/createNested.cpp \
    $$PWD/extras/tests/JsonDocument/isNull.cpp \
    $$PWD/extras/tests/JsonDocument/nesting.cpp \
    $$PWD/extras/tests/JsonDocument/overflowed.cpp \
    $$PWD/extras/tests/JsonDocument/remove.cpp \
    $$PWD/extras/tests/JsonDocument/shrinkToFit.cpp \
    $$PWD/extras/tests/JsonDocument/size.cpp \
    $$PWD/extras/tests/JsonDocument/subscript.cpp \
    $$PWD/extras/tests/JsonObject/clear.cpp \
    $$PWD/extras/tests/JsonObject/containsKey.cpp \
    $$PWD/extras/tests/JsonObject/copy.cpp \
    $$PWD/extras/tests/JsonObject/createNestedArray.cpp \
    $$PWD/extras/tests/JsonObject/createNestedObject.cpp \
    $$PWD/extras/tests/JsonObject/equals.cpp \
    $$PWD/extras/tests/JsonObject/invalid.cpp \
    $$PWD/extras/tests/JsonObject/isNull.cpp \
    $$PWD/extras/tests/JsonObject/iterator.cpp \
    $$PWD/extras/tests/JsonObject/memoryUsage.cpp \
    $$PWD/extras/tests/JsonObject/nesting.cpp \
    $$PWD/extras/tests/JsonObject/remove.cpp \
    $$PWD/extras/tests/JsonObject/size.cpp \
    $$PWD/extras/tests/JsonObject/std_string.cpp \
    $$PWD/extras/tests/JsonObject/subscript.cpp \
    $$PWD/extras/tests/JsonSerializer/CustomWriter.cpp \
    $$PWD/extras/tests/JsonSerializer/JsonArray.cpp \
    $$PWD/extras/tests/JsonSerializer/JsonArrayPretty.cpp \
    $$PWD/extras/tests/JsonSerializer/JsonObject.cpp \
    $$PWD/extras/tests/JsonSerializer/JsonObjectPretty.cpp \
    $$PWD/extras/tests/JsonSerializer/JsonVariant.cpp \
    $$PWD/extras/tests/JsonSerializer/misc.cpp \
    $$PWD/extras/tests/JsonSerializer/std_stream.cpp \
    $$PWD/extras/tests/JsonSerializer/std_string.cpp \
    $$PWD/extras/tests/JsonVariant/add.cpp \
    $$PWD/extras/tests/JsonVariant/as.cpp \
    $$PWD/extras/tests/JsonVariant/clear.cpp \
    $$PWD/extras/tests/JsonVariant/compare.cpp \
    $$PWD/extras/tests/JsonVariant/containsKey.cpp \
    $$PWD/extras/tests/JsonVariant/converters.cpp \
    $$PWD/extras/tests/JsonVariant/copy.cpp \
    $$PWD/extras/tests/JsonVariant/createNested.cpp \
    $$PWD/extras/tests/JsonVariant/is.cpp \
    $$PWD/extras/tests/JsonVariant/isnull.cpp \
    $$PWD/extras/tests/JsonVariant/memoryUsage.cpp \
    $$PWD/extras/tests/JsonVariant/misc.cpp \
    $$PWD/extras/tests/JsonVariant/nesting.cpp \
    $$PWD/extras/tests/JsonVariant/or.cpp \
    $$PWD/extras/tests/JsonVariant/overflow.cpp \
    $$PWD/extras/tests/JsonVariant/remove.cpp \
    $$PWD/extras/tests/JsonVariant/set.cpp \
    $$PWD/extras/tests/JsonVariant/subscript.cpp \
    $$PWD/extras/tests/JsonVariant/types.cpp \
    $$PWD/extras/tests/JsonVariant/undefined.cpp \
    $$PWD/extras/tests/MemoryPool/StringCopier.cpp \
    $$PWD/extras/tests/MemoryPool/allocVariant.cpp \
    $$PWD/extras/tests/MemoryPool/clear.cpp \
    $$PWD/extras/tests/MemoryPool/saveString.cpp \
    $$PWD/extras/tests/MemoryPool/size.cpp \
    $$PWD/extras/tests/Misc/FloatParts.cpp \
    $$PWD/extras/tests/Misc/JsonString.cpp \
    $$PWD/extras/tests/Misc/Readers.cpp \
    $$PWD/extras/tests/Misc/StringAdapters.cpp \
    $$PWD/extras/tests/Misc/StringWriter.cpp \
    $$PWD/extras/tests/Misc/TypeTraits.cpp \
    $$PWD/extras/tests/Misc/Utf16.cpp \
    $$PWD/extras/tests/Misc/Utf8.cpp \
    $$PWD/extras/tests/Misc/arithmeticCompare.cpp \
    $$PWD/extras/tests/Misc/conflicts.cpp \
    $$PWD/extras/tests/Misc/deprecated.cpp \
    $$PWD/extras/tests/Misc/printable.cpp \
    $$PWD/extras/tests/Misc/unsigned_char.cpp \
    $$PWD/extras/tests/Misc/version.cpp \
    $$PWD/extras/tests/MixedConfiguration/decode_unicode_0.cpp \
    $$PWD/extras/tests/MixedConfiguration/decode_unicode_1.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_alignment_0.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_alignment_1.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_comments_0.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_comments_1.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_infinity_0.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_infinity_1.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_nan_0.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_nan_1.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_progmem_1.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_string_deduplication_0.cpp \
    $$PWD/extras/tests/MixedConfiguration/enable_string_deduplication_1.cpp \
    $$PWD/extras/tests/MixedConfiguration/use_double_0.cpp \
    $$PWD/extras/tests/MixedConfiguration/use_double_1.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/deserializeArray.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/deserializeObject.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/deserializeStaticVariant.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/deserializeVariant.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/doubleToFloat.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/filter.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/incompleteInput.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/input_types.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/misc.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/nestingLimit.cpp \
    $$PWD/extras/tests/MsgPackDeserializer/notSupported.cpp \
    $$PWD/extras/tests/MsgPackSerializer/destination_types.cpp \
    $$PWD/extras/tests/MsgPackSerializer/measure.cpp \
    $$PWD/extras/tests/MsgPackSerializer/misc.cpp \
    $$PWD/extras/tests/MsgPackSerializer/serializeArray.cpp \
    $$PWD/extras/tests/MsgPackSerializer/serializeObject.cpp \
    $$PWD/extras/tests/MsgPackSerializer/serializeVariant.cpp \
    $$PWD/extras/tests/Numbers/convertNumber.cpp \
    $$PWD/extras/tests/Numbers/parseDouble.cpp \
    $$PWD/extras/tests/Numbers/parseFloat.cpp \
    $$PWD/extras/tests/Numbers/parseInteger.cpp \
    $$PWD/extras/tests/Numbers/parseNumber.cpp \
    $$PWD/extras/tests/TextFormatter/writeFloat.cpp \
    $$PWD/extras/tests/TextFormatter/writeInteger.cpp \
    $$PWD/extras/tests/TextFormatter/writeString.cpp \
    $$PWD/extras/tests/catch/catch.cpp
